apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name.prefix" . }}metrics
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.common.namespace }}
  name: {{ include "name.prefix" . }}admin
rules:
  - verbs: ["*"]
    apiGroups: ["*"]
    resources: ["*"]
