apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "name.prefix" . }}pvc
  namespace: {{ .Values.common.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ include "name.prefix" . }}storageclass
  #storageClassName: default
