apiVersion: v1
kind: ConfigMap
metadata:
  name: hw-configmap-nginx
  namespace: homework
data:
  default.conf: |
    server {
        server_name  localhost;
        listen 8080;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        location /stub_status {
            stub_status on;
        }
    }