apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
  namespace: homework
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-conf-volume
          configMap:
            name: hw-configmap-nginx
            optional: false
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf-volume
          readinessProbe:
            httpGet:
              path: /stub_status
              port: 8080
          ports:
            - name: http
              containerPort: 8080
        - name: nginx-metrics-exporter
          image: nginx/nginx-prometheus-exporter:1.4.0
          ports:
            - name: nginx-metrics
              containerPort: 9113
          args: ['--nginx.scrape-uri=http://localhost:8080/stub_status']

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1