apiVersion: v1
kind: ConfigMap
metadata:
  name: hw-configmap
  namespace: homework
data:
  file: |
    key1=value1
    key2=value2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hw-configmap-nginx
  namespace: homework
data:
  default.conf: |
    server {
        server_name  localhost;
        listen 80;
        root /homework;
        location / {
            root   /homework;
        }
        location /conf {
            root /homework/conf;
        }
    }