apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuber-hw-04-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: kuber-hw-04-storageclass
  #storageClassName: default
