apiVersion: v1
kind: Pod
metadata:
  name: kuber-hw-01-pod
  namespace: homework
spec:
  volumes:
    - name: kuber-hw-01-volume
      emptyDir: {}
  initContainers:
    - name: init-container
      image: busybox:latest
      command: ['sh', '-c', 'wget -O /init/index.html https://example.com']
      volumeMounts:
        - mountPath: /init
          name: kuber-hw-01-volume
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8000
      volumeMounts:
        - mountPath: /homework
          name: kuber-hw-01-volume
      lifecycle:
        preStop:
          exec:
            command: ['sh', '-c', 'rm -f /homework/index.html']
  restartPolicy: Always